import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const staticExtensions = new Set([
  ".js",
  ".css",
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".svg",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".avif",
  ".ico",
]);

function resourcePath(value) {
  if (
    typeof value !== "string" ||
    !value ||
    value.startsWith("/") ||
    /[\\:?#%\u0000-\u001f]/.test(value) ||
    value.split("/").some((part) => !part || part === "." || part === "..")
  ) {
    throw new Error(`Invalid static resource path: ${value}`);
  }
  return value;
}

function isShellResource(value) {
  return (
    value === "index.html" ||
    (path.posix.basename(value) !== "sw.js" &&
      staticExtensions.has(path.posix.extname(value).toLowerCase()))
  );
}

// Pure: caller supplies paths and bytes; no directory is read or written here.
export function buildManifest(files) {
  const resources = files
    .map(({ path: filename, contents }) => ({
      path: resourcePath(filename),
      contents,
    }))
    .filter((file) => isShellResource(file.path))
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  if (!resources.some((file) => file.path === "index.html")) {
    throw new Error("Offline shell requires index.html");
  }
  if (new Set(resources.map((file) => file.path)).size !== resources.length) {
    throw new Error("Offline shell contains duplicate paths");
  }
  const hash = createHash("sha256");
  for (const file of resources) {
    const contents = Buffer.from(file.contents);
    hash.update(JSON.stringify([file.path, contents.length]));
    hash.update(contents);
  }
  return {
    version: hash.digest("hex"),
    resources: resources.map((file) => file.path),
  };
}

export function buildWorkerSource(manifest) {
  if (!/^[a-f0-9]{64}$/.test(manifest.version)) {
    throw new Error("Invalid offline shell version");
  }
  const resources = manifest.resources.map(resourcePath);
  if (
    !resources.includes("index.html") ||
    !resources.every(isShellResource) ||
    new Set(resources).size !== resources.length
  ) {
    throw new Error("Invalid offline shell resources");
  }
  return `// Generated by scripts/build-offline.mjs. Only static build resources are cached.
const SCOPE = new URL(self.registration.scope);
const CACHE_PREFIX = "emergence-lab-shell:" + encodeURIComponent(SCOPE.pathname) + ":";
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(manifest.version)};
const RESOURCES = ${JSON.stringify(resources)}.map((path) => new URL(path, SCOPE).href);
const RESOURCE_URLS = new Set(RESOURCES);
const INDEX_URL = new URL("index.html", SCOPE).href;

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(RESOURCES.map((url) => new Request(url, { cache: "reload" })));
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== SCOPE.origin || !url.pathname.startsWith(SCOPE.pathname)) return;

  if (request.mode === "navigate") {
    event.respondWith((async () => {
      try {
        const response = await fetch(request);
        if (response.ok) return response;
        const cached = await (await caches.open(CACHE_NAME)).match(INDEX_URL);
        return cached || response;
      } catch (error) {
        const cached = await (await caches.open(CACHE_NAME)).match(INDEX_URL);
        if (cached) return cached;
        throw error;
      }
    })());
    return;
  }

  if (!RESOURCE_URLS.has(url.href)) return;
  event.respondWith((async () => {
    const cached = await (await caches.open(CACHE_NAME)).match(request);
    return cached || fetch(request);
  })());
});
`;
}

async function readDistFiles(directory, prefix = "") {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const filename = prefix + entry.name;
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await readDistFiles(absolute, filename + "/")));
    } else if (entry.isFile() && isShellResource(filename)) {
      files.push({ path: filename, contents: await readFile(absolute) });
    }
  }
  return files;
}

export async function writeOfflineWorker(directory) {
  const manifest = buildManifest(await readDistFiles(directory));
  await writeFile(
    path.join(directory, "sw.js"),
    buildWorkerSource(manifest),
    "utf8",
  );
  return manifest;
}

// Importing the pure builders in tests must never modify a real dist directory.
if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const manifest = await writeOfflineWorker(path.resolve("dist"));
  console.log(
    `Offline shell: ${manifest.resources.length} resources, version ${manifest.version.slice(0, 12)}`,
  );
}
